#!/bin/sh -eux

PASS=0

cleanup() {
    [ "$PASS" = "1" ] || (echo FAIL && exit 1)
}

trap cleanup EXIT HUP INT TERM

LXCFSDIR=${LXCFSDIR:-/var/lib/lxcfs}

if ! mountpoint -q ${LXCFSDIR}; then
    echo "lxcfs isn't mounted on ${LXCFSDIR}"
    exit 1
fi

cgm remove all lxcfs_test_proc || true
cgm create all lxcfs_test_proc
cgm removeonempty all lxcfs_test_proc
cgm movepid all lxcfs_test_proc $$

cgm setvalue memory $(cgm getpidcgroupabs memory $$) \
    memory.limit_in_bytes $((1024*1024))
cgm setvalue cpuset $(cgm getpidcgroupabs cpuset $$) \
    cpuset.cpus 0

# Test cpuinfo
[ "$(grep "^processor" ${LXCFSDIR}/proc/cpuinfo | wc -l)" = "1" ]
grep -q "^processor.*0$" ${LXCFSDIR}/proc/cpuinfo

# Test stat
[ "$(grep "^cpu" ${LXCFSDIR}/proc/stat | wc -l)" = "2" ]

# Test meminfo
grep -q "^MemTotal.*1024 kB$" ${LXCFSDIR}/proc/meminfo

# Test uptime
if [ -e /proc/self/ns/user ]; then
    [ "$(lxc-unshare -s 'USER|PID' cat ${LXCFSDIR}/proc/uptime)" = "0.0 0.0" ]
fi

PASS=1
echo PASS
