name: Builds
on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  coverity:
    name: Coverity
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Coverity Build Tool
        run: |
          wget -q https://scan.coverity.com/download/cxx/linux64 --post-data "token=$TOKEN&project=lxc/lxcfs" -O cov-analysis-linux64.tar.gz
          mkdir cov-analysis-linux64
          tar xzf cov-analysis-linux64.tar.gz --strip 1 -C cov-analysis-linux64
        env:
          TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}

      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq gcc clang
          sudo apt-get install -qq libfuse-dev uuid-runtime
          sudo apt-get install -qq python3 python3-setuptools
          sudo pip3 install meson ninja

      - name: Run coverity
        run: |
          export PATH="$(pwd)/cov-analysis-linux64/bin:${PATH}"

          meson setup -Ddocs=false -Dtests=true -Dinit-script=systemd -Dprefix=/usr build/

          # Build
          cov-build --dir cov-int ninja -C build
          tar czvf lxcfs.tgz cov-int

          # Submit the results
          curl \
            --form project=lxc/lxcfs \
            --form token=${TOKEN} \
            --form email=lxc-devel@lists.linuxcontainers.org \
            --form file=@lxcfs.tgz \
            --form version=master \
            --form description="${GITHUB_SHA}" \
            https://scan.coverity.com/builds?project=lxc/lxcfs
        env:
          TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}
